In [9]:
import numpy as np
array = np.random.randint(1, 51, size=(5, 4))
print("Original Array:\n", array)

Original Array:
 [[ 7 47 37 50]
 [19 34 16  2]
 [29 40 45 21]
 [28 44 45 48]
 [16 11 31 38]]


In [10]:
anti_diagonal = [int(array[i, -1 - i]) for i in range(min(array.shape))]
print("Anti-diagonal elements:", anti_diagonal)

Anti-diagonal elements: [50, 16, 40, 28]


In [11]:
row_max = np.max(array, axis=1)
print("Maximum value in each row:", row_max)

Maximum value in each row: [50 34 45 48 38]


In [12]:
mean_value = np.mean(array)
less_equal_mean = array[array <= mean_value]
print("Elements less than or equal to mean (", mean_value, "):", less_equal_mean)

Elements less than or equal to mean ( 30.4 ): [ 7 19 16  2 29 21 28 16 11]


In [13]:
def numpy_boundary_traversal(matrix):
    if matrix.ndim != 2:
        raise ValueError("Input must be a 2D NumPy array.")
    top = matrix[0, :]
    right = matrix[1:-1, -1]
    bottom = matrix[-1, ::-1]
    left = matrix[-2:0:-1, 0]
    return np.concatenate((top, right, bottom, left)).tolist()

# Test the function
boundary = numpy_boundary_traversal(array)
print(boundary)

[7, 47, 37, 50, 2, 21, 48, 38, 31, 11, 16, 28, 29, 19]
